name: Make CCL Cocoa App

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Specify release tag to build from https://github.com/Clozure/ccl/releases/ repo. Omit the v!!!'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-12, macos-10.15]

    steps:
    - name: Get CCL source code and bootstrap
      run: |
        wget "https://github.com/Clozure/ccl/archive/refs/tags/v${{ github.event.inputs.release }}.tar.gz"
        tar xfz "v${{ github.event.inputs.release }}.tar.gz"
        cd "ccl-${{ github.event.inputs.release }}/"
        wget "https://github.com/Clozure/ccl/releases/download/v${{ github.event.inputs.release }}/darwinx86.tar.gz"
        tar xf darwinx86.tar.gz
      
    - name: Build Clozure CCL Cocoa App
      run: |
        cd "ccl-${{ github.event.inputs.release }}"
        ./dx86cl64 --eval '(REQUIRE "COCOA-APPLICATION")'

    - name: Package CCL app
      run: |
        mkdir ccl-app
        mv "ccl-${{ github.event.inputs.release }}/Clozure CL64.app" ccl-app/
        hdiutil create -srcfolder ccl-app/ -volname 'Clozure CL64' -fs HFS+ -fsargs "-c c=64,a=16,e=16" -format UDZO -imagekey zlib-level=9 "Clozure CL64 ${{ github.event.inputs.release }}-${{ matrix.os }}.dmg"
     
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        file: "Clozure CL64 ${{ github.event.inputs.release }}-${{ matrix.os }}.dmg"
        asset_name: "Clozure CL64 App v${{ github.event.inputs.release }} for ${{ matrix.os }}.dmg"
        tag: "v${{ github.event.inputs.release }}"
        overwrite: true

